## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)
library(ggplot2)
library(scales)
library(gghighlight)
library(ICIKendallTau)
library(visualizationQualityControl)
library(dplyr)
library(rmarkdown)
library(tidyr)
library(knitrProgressBar)
library(furrr)
library(rlang)
library(patchwork)
library(xfun)
library(ggforce)
library(flextable)
library(documentNumbering)
#library(magick)
options(parallelly.fork.enable = TRUE)
future::plan(multicore)
theme_set(cowplot::theme_cowplot())
paint::mask_print()
